name: Terraform Pipeline

on:
  push:
    branches:
      - main
    paths:
     - 'terraform/**'
  pull_request:
    types: [opened, reopened]

jobs:
  terraform:
    if: contains(github.event.head_commit.message, '[terraform]')
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Initialize Terraform
        working-directory: terraform
        run: terraform init

      - name: Plan Terraform
        working-directory: terraform
        run: terraform plan

      - name: Apply Terraform
        working-directory: terraform
        run: terraform apply -auto-approve
